name: Lint the code

on:
  push:
    paths:
      - 'src/**'
      - '**/*.json'
  pull_request:
    paths:
      - 'src/**'
      - '**/*.json'

jobs:
  lint:
    name: Lint the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .
